name: "Terraform Plan"

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Pay-As-You-Go (9d81bd49-f6ee-4775-a938-63fb5e15f2a2)'
    backendAzureRmResourceGroupName: 'phoenixtech-tfstate-rg'
    backendAzureRmStorageAccountName: 'mwtfstateyqpqj'
    backendAzureRmContainerName: 'core-tfstate'
    backendAzureRmKey: 'tf/terraform.state'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'custom'
    customCommand: 'plan'
    outputTo: 'file'
    fileName: 'plan'
    environmentServiceNameAzureRM: 'Pay-As-You-Go (9d81bd49-f6ee-4775-a938-63fb5e15f2a2)'
  
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/plan'
    artifactName: 'terraformPlan'
    publishLocation: 'Container'
